#!/usr/bin/env bash

# Get the winsnap folder
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Get the active window ID
win=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f2)

# Determine the size and position of the active window.
parse_win_data () {
    woff=$(( $3 * 2 ))
    hoff=$(( $3 + $4 ))
    x=$(( $1 - $3 ))
    y=$(( $2 - $4 ))
    w=$(( $5 + $woff ))
    h=$(( $6 + $hoff ))
}
parse_win_data $(xwininfo -id "$win" \
    | grep -E "upper-left|Width:|Height:" | cut -d: -f2 | xargs echo)

# Invoke the winsnap-go program with our window geometry, then move it.
move_win () {
    x=$1
    y=$2
    w=$(($3 - $woff))
    h=$(($4 - $hoff))
    wmctrl -i -r "$win" -e "0,$x,$y,$w,$h"
}
move_win $($dir/winsnap-go $1 $x $y $w $h)
