#!/usr/bin/env bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

get_win_data () {
    parse_win_data $(xwininfo -id "$1" \
        | grep -E "upper-left|Width:|Height:" | cut -d: -f2 | xargs echo)
}

parse_win_data () {
    woff=$(( $3 * 2 ))
    hoff=$(( $3 + $4 ))
    x=$(( $1 - $3 ))
    y=$(( $2 - $4 ))
    w=$(( $5 + $woff ))
    h=$(( $6 + $hoff ))
}

move_win () {
    get_win_data "$1"
    local nx=$2
    local ny=$3
    local nw=$(($4 - $woff))
    local nh=$(($5 - $hoff))
    wmctrl -i -r "$1" -e "0,$nx,$ny,$nw,$nh"
}

do_snap_or_next () {
    local win=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f2)
    get_win_data "$win"
    move_win "$win" $($dir/winsnap-go $1 $2 $x $y $w $h)
}

get_swap_params () {
    local wins=$(wmctrl -l | grep -v -E "Desktop|xfce4-panel" | awk '{print $1":"$2}')
    for win in $wins; do
        local data=($(echo $win | sed 's/:/ /'))
        get_win_data "${data[0]}"
        printf " ${data[0]} ${data[1]} $x $y $w $h"
    done
    echo ""
}

do_swap () {
    local params=$(get_swap_params)
    local new_data=$($dir/winsnap-go swap $params)
    echo "$new_data"
}

case "$1" in
    snap)
        do_snap_or_next $1 $2
        ;;
    next)
        do_snap_or_next $1 $2
        ;;
    swap)
        do_swap
        ;;
esac






